/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org */
        get: operations["get_org_api_org_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Org */
        patch: operations["update_org_api_org_patch"];
        trace?: never;
    };
    "/api/organisations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_organisations__org_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_organisations__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organisations */
        get: operations["list_organisations_api_admin_organisations_get"];
        put?: never;
        /** Create Organisation */
        post: operations["create_organisation_api_admin_organisations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organisations/{org_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Plan */
        post: operations["assign_plan_api_admin_organisations__org_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_admin_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_admin_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_admin_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Update Plan */
        patch: operations["update_plan_api_admin_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_api_services__service_id__get"];
        put?: never;
        post?: never;
        /** Archive Service */
        delete: operations["archive_service_api_services__service_id__delete"];
        options?: never;
        head?: never;
        /** Update Service */
        patch: operations["update_service_api_services__service_id__patch"];
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_clients__client_id__get"];
        put?: never;
        post?: never;
        /** Archive Client */
        delete: operations["archive_client_api_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_api_clients__client_id__patch"];
        trace?: never;
    };
    "/api/clients/{client_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_clients__client_id__notes_get"];
        put?: never;
        /** Add Note */
        post: operations["add_note_api_clients__client_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Subscriptions */
        get: operations["list_client_subscriptions_api_clients__client_id__subscriptions_get"];
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_api_clients__client_id__subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Invoices */
        get: operations["list_client_invoices_api_clients__client_id__invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Enrollments */
        get: operations["list_client_enrollments_api_clients__client_id__enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instructors */
        get: operations["list_instructors_api_instructors_get"];
        put?: never;
        /** Create Instructor */
        post: operations["create_instructor_api_instructors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instructors/{instructor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instructor */
        get: operations["get_instructor_api_instructors__instructor_id__get"];
        put?: never;
        post?: never;
        /** Archive Instructor */
        delete: operations["archive_instructor_api_instructors__instructor_id__delete"];
        options?: never;
        head?: never;
        /** Update Instructor */
        patch: operations["update_instructor_api_instructors__instructor_id__patch"];
        trace?: never;
    };
    "/api/instructors/{instructor_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batches Taught */
        get: operations["batches_taught_api_instructors__instructor_id__batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location */
        get: operations["get_location_api_locations__location_id__get"];
        put?: never;
        post?: never;
        /** Archive Location */
        delete: operations["archive_location_api_locations__location_id__delete"];
        options?: never;
        head?: never;
        /** Update Location */
        patch: operations["update_location_api_locations__location_id__patch"];
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        /** Archive Batch */
        delete: operations["archive_batch_api_batches__batch_id__delete"];
        options?: never;
        head?: never;
        /** Update Batch */
        patch: operations["update_batch_api_batches__batch_id__patch"];
        trace?: never;
    };
    "/api/batches/{batch_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch Roster */
        get: operations["batch_roster_api_batches__batch_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enrollments */
        get: operations["list_enrollments_api_enrollments_get"];
        put?: never;
        /** Create Enrollment */
        post: operations["create_enrollment_api_enrollments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Subscription */
        patch: operations["update_subscription_api_subscriptions__subscription_id__patch"];
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_api_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/generate-missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Missing Invoices */
        post: operations["generate_missing_invoices_api_invoices_generate_missing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Invoice */
        patch: operations["update_invoice_api_invoices__invoice_id__patch"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "Individual" | "Corporate" | "Family";
        /** AdminOrgIn */
        AdminOrgIn: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            admin: components["schemas"]["MemberIn"];
        };
        /** AdminOrgOut */
        AdminOrgOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Plan Id */
            plan_id: string | null;
            /** Plan Name */
            plan_name?: string | null;
            /** Subscription Starts On */
            subscription_starts_on: string | null;
            /** Subscription Ends On */
            subscription_ends_on: string | null;
            /** Subscription State */
            subscription_state: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Client Count
             * @default 0
             */
            client_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AssignPlanIn */
        AssignPlanIn: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Starts On */
            starts_on?: string | null;
        };
        /** BatchIn */
        BatchIn: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** @default upcoming */
            status: components["schemas"]["BatchStatus"];
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /**
             * Instructor Id
             * Format: uuid
             */
            instructor_id: string;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Description */
            description?: string | null;
        };
        /** BatchOut */
        BatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            status: components["schemas"]["BatchStatus"];
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /**
             * Instructor Id
             * Format: uuid
             */
            instructor_id: string;
            /** Location Name */
            location_name?: string | null;
            /** Instructor Name */
            instructor_name?: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Description */
            description: string | null;
            /**
             * Enrolled Count
             * @default 0
             */
            enrolled_count: number;
            /** Capacity */
            capacity?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BatchPatch */
        BatchPatch: {
            /** Name */
            name?: string | null;
            /** Code */
            code?: string | null;
            status?: components["schemas"]["BatchStatus"] | null;
            /** Location Id */
            location_id?: string | null;
            /** Instructor Id */
            instructor_id?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * BatchStatus
         * @enum {string}
         */
        BatchStatus: "active" | "inactive" | "upcoming" | "completed";
        /**
         * BillingInterval
         * @enum {string}
         */
        BillingInterval: "N/A" | "Monthly" | "Weekly" | "Quarterly" | "Semi-Annual" | "Annual";
        /**
         * CancellationPolicy
         * @enum {string}
         */
        CancellationPolicy: "Non-Refundable" | "Flexible" | "Moderate" | "Strict";
        /**
         * CapacityPolicy
         * @enum {string}
         */
        CapacityPolicy: "warn" | "block";
        /** ClientIn */
        ClientIn: {
            /** Name */
            name: string;
            /** Name Hint */
            name_hint?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Lead Source */
            lead_source?: string | null;
            /** @default Lead */
            lifecycle_stage: components["schemas"]["LifecycleStage"];
            /**
             * Do Not Contact
             * @default false
             */
            do_not_contact: boolean;
            /**
             * Do Not Email
             * @default false
             */
            do_not_email: boolean;
            /**
             * Do Not Call
             * @default false
             */
            do_not_call: boolean;
            /** Address */
            address?: string | null;
            /** Work */
            work?: string | null;
            /** Description */
            description?: string | null;
            /** @default Individual */
            account_type: components["schemas"]["AccountType"];
            /** Company Name */
            company_name?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Company Contact */
            company_contact?: string | null;
            /** Family Link Id */
            family_link_id?: string | null;
        };
        /** ClientOut */
        ClientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Name Hint */
            name_hint: string | null;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            gender: components["schemas"]["Gender"] | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Lead Source */
            lead_source: string | null;
            lifecycle_stage: components["schemas"]["LifecycleStage"];
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Do Not Email */
            do_not_email: boolean;
            /** Do Not Call */
            do_not_call: boolean;
            /** Address */
            address: string | null;
            /** Work */
            work: string | null;
            /** Description */
            description: string | null;
            account_type: components["schemas"]["AccountType"];
            /** Company Name */
            company_name: string | null;
            /** Gstin */
            gstin: string | null;
            /** Company Contact */
            company_contact: string | null;
            /** Family Link Id */
            family_link_id: string | null;
            /** Family Link Name */
            family_link_name?: string | null;
            /**
             * Linked By
             * @default []
             */
            linked_by: components["schemas"]["ClientRef"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClientPatch */
        ClientPatch: {
            /** Name */
            name?: string | null;
            /** Name Hint */
            name_hint?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Lead Source */
            lead_source?: string | null;
            lifecycle_stage?: components["schemas"]["LifecycleStage"] | null;
            /** Do Not Contact */
            do_not_contact?: boolean | null;
            /** Do Not Email */
            do_not_email?: boolean | null;
            /** Do Not Call */
            do_not_call?: boolean | null;
            /** Address */
            address?: string | null;
            /** Work */
            work?: string | null;
            /** Description */
            description?: string | null;
            account_type?: components["schemas"]["AccountType"] | null;
            /** Company Name */
            company_name?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Company Contact */
            company_contact?: string | null;
            /** Family Link Id */
            family_link_id?: string | null;
        };
        /** ClientRef */
        ClientRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** DashboardBatch */
        DashboardBatch: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Instructor Name */
            instructor_name: string | null;
            /** Location Name */
            location_name: string | null;
            /** Enrolled Count */
            enrolled_count: number;
            /** Capacity */
            capacity: number | null;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Active Clients */
            active_clients: number;
            /** Active Batches */
            active_batches: number;
            /** Billed This Month */
            billed_this_month: string;
            /** Overdue Count */
            overdue_count: number;
            /** Todays Batches */
            todays_batches: components["schemas"]["DashboardBatch"][];
            /** Recent Enrollments */
            recent_enrollments: components["schemas"]["EnrollmentOut"][];
        };
        /** DeliverableIn */
        DeliverableIn: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
        };
        /** DeliverableOut */
        DeliverableOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
        };
        /**
         * DeliveryMode
         * @enum {string}
         */
        DeliveryMode: "Offline" | "Online" | "Hybrid" | "Self Service";
        /** EnrollmentIn */
        EnrollmentIn: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** EnrollmentOut */
        EnrollmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Client Name */
            client_name?: string | null;
            /** Batch Name */
            batch_name?: string | null;
            /** Batch Code */
            batch_code?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Capacity Warning */
            capacity_warning?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "Female" | "Male" | "Non-binary" | "Prefer not to say";
        /** GenerateMissingIn */
        GenerateMissingIn: {
            /** Client Id */
            client_id?: string | null;
        };
        /** GenerateMissingOut */
        GenerateMissingOut: {
            /** Created */
            created: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstructorIn */
        InstructorIn: {
            /** Name */
            name: string;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /** Experience At Joining */
            experience_at_joining?: number | string | null;
            /** Courses */
            courses?: string | null;
            /** Certifications */
            certifications?: string | null;
            /** Joining Date */
            joining_date?: string | null;
        };
        /** InstructorOut */
        InstructorOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Address */
            address: string | null;
            /** Phone */
            phone: string | null;
            /** Skills */
            skills: string[];
            /** Experience At Joining */
            experience_at_joining: string | null;
            /** Courses */
            courses: string | null;
            /** Certifications */
            certifications: string | null;
            /** Joining Date */
            joining_date: string | null;
            /** Age */
            age?: number | null;
            /** Current Experience */
            current_experience?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InstructorPatch */
        InstructorPatch: {
            /** Name */
            name?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Skills */
            skills?: string[] | null;
            /** Experience At Joining */
            experience_at_joining?: number | string | null;
            /** Courses */
            courses?: string | null;
            /** Certifications */
            certifications?: string | null;
            /** Joining Date */
            joining_date?: string | null;
        };
        /** InvoiceOut */
        InvoiceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Subscription Id
             * Format: uuid
             */
            subscription_id: string;
            /** Client Name */
            client_name?: string | null;
            /** Service Name */
            service_name?: string | null;
            /** Period Label */
            period_label: string;
            /**
             * Issue Date
             * Format: date
             */
            issue_date: string;
            /** Amount */
            amount: string;
            status: components["schemas"]["InvoiceStatus"];
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InvoicePage */
        InvoicePage: {
            /** Items */
            items: components["schemas"]["InvoiceOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
            /**
             * Outstanding Total
             * @default 0
             */
            outstanding_total: string;
        };
        /** InvoicePatch */
        InvoicePatch: {
            status: components["schemas"]["InvoiceStatus"];
        };
        /**
         * InvoiceStatus
         * @enum {string}
         */
        InvoiceStatus: "due" | "paid" | "void";
        /**
         * LifecycleStage
         * @enum {string}
         */
        LifecycleStage: "Lead" | "Prospect" | "Customer" | "Lapsed";
        /** LocationIn */
        LocationIn: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Type */
            type?: string | null;
            /** Address */
            address?: string | null;
            /** Capacity Per Batch */
            capacity_per_batch?: number | null;
            /** Parallel Batches */
            parallel_batches?: number | null;
        };
        /** LocationOut */
        LocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Type */
            type: string | null;
            /** Address */
            address: string | null;
            /** Capacity Per Batch */
            capacity_per_batch: number | null;
            /** Parallel Batches */
            parallel_batches: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LocationPatch */
        LocationPatch: {
            /** Name */
            name?: string | null;
            /** Code */
            code?: string | null;
            /** Type */
            type?: string | null;
            /** Address */
            address?: string | null;
            /** Capacity Per Batch */
            capacity_per_batch?: number | null;
            /** Parallel Batches */
            parallel_batches?: number | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Org Code */
            org_code: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MemberIn */
        MemberIn: {
            /** Name */
            name: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            role: components["schemas"]["Role"];
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Username */
            username: string;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NoteIn */
        NoteIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Channel */
            channel: string;
            /** Text */
            text: string;
        };
        /** NoteOut */
        NoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Channel */
            channel: string;
            /** Text */
            text: string;
            /** Author Name */
            author_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrgSettingsOut */
        OrgSettingsOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Currency */
            currency: string;
            /** Timezone */
            timezone: string;
            /** Invoice Prefix */
            invoice_prefix: string;
            /** Invoice Grace Days */
            invoice_grace_days: number;
            capacity_policy: components["schemas"]["CapacityPolicy"];
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Subscription Starts On */
            subscription_starts_on: string | null;
            /** Subscription Ends On */
            subscription_ends_on: string | null;
        };
        /** OrgSettingsPatch */
        OrgSettingsPatch: {
            /** Name */
            name?: string | null;
            /** Currency */
            currency?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Invoice Prefix */
            invoice_prefix?: string | null;
            /** Invoice Grace Days */
            invoice_grace_days?: number | null;
            capacity_policy?: components["schemas"]["CapacityPolicy"] | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** OrgSummary */
        OrgSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
        };
        /** Page[BatchOut] */
        Page_BatchOut_: {
            /** Items */
            items: components["schemas"]["BatchOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[ClientOut] */
        Page_ClientOut_: {
            /** Items */
            items: components["schemas"]["ClientOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[EnrollmentOut] */
        Page_EnrollmentOut_: {
            /** Items */
            items: components["schemas"]["EnrollmentOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[InstructorOut] */
        Page_InstructorOut_: {
            /** Items */
            items: components["schemas"]["InstructorOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[LocationOut] */
        Page_LocationOut_: {
            /** Items */
            items: components["schemas"]["LocationOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[ServiceOut] */
        Page_ServiceOut_: {
            /** Items */
            items: components["schemas"]["ServiceOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** PlanIn */
        PlanIn: {
            /** Name */
            name: string;
            /** Amount */
            amount: number | string;
            /** No Of Days */
            no_of_days: number;
            /** Description */
            description?: string | null;
        };
        /** PlanOut */
        PlanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Amount */
            amount: string;
            /** No Of Days */
            no_of_days: number;
            /** Description */
            description: string | null;
            /**
             * Orgs In Use
             * @default 0
             */
            orgs_in_use: number;
        };
        /** PlanPatch */
        PlanPatch: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** No Of Days */
            no_of_days?: number | null;
            /** Description */
            description?: string | null;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "superadmin" | "admin" | "staff";
        /** ServiceIn */
        ServiceIn: {
            /** Name */
            name: string;
            /** Sku */
            sku: string;
            /** Description */
            description?: string | null;
            service_type: components["schemas"]["ServiceType"];
            delivery_mode: components["schemas"]["DeliveryMode"];
            /** Max Capacity */
            max_capacity?: number | null;
            /** @default N/A */
            billing_interval: components["schemas"]["BillingInterval"];
            /** Rate */
            rate: number | string;
            /** @default Flexible */
            cancellation_policy: components["schemas"]["CancellationPolicy"];
            /**
             * Pricing Options
             * @default []
             */
            pricing_options: string[];
            /**
             * Deliverables
             * @default []
             */
            deliverables: components["schemas"]["DeliverableIn"][];
        };
        /** ServiceOut */
        ServiceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Sku */
            sku: string;
            /** Description */
            description: string | null;
            service_type: components["schemas"]["ServiceType"];
            delivery_mode: components["schemas"]["DeliveryMode"];
            /** Max Capacity */
            max_capacity: number | null;
            billing_interval: components["schemas"]["BillingInterval"];
            /** Rate */
            rate: string;
            cancellation_policy: components["schemas"]["CancellationPolicy"];
            /** Pricing Options */
            pricing_options: string[];
            /** Deliverables */
            deliverables: components["schemas"]["DeliverableOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ServicePatch */
        ServicePatch: {
            /** Name */
            name?: string | null;
            /** Sku */
            sku?: string | null;
            /** Description */
            description?: string | null;
            service_type?: components["schemas"]["ServiceType"] | null;
            delivery_mode?: components["schemas"]["DeliveryMode"] | null;
            /** Max Capacity */
            max_capacity?: number | null;
            billing_interval?: components["schemas"]["BillingInterval"] | null;
            /** Rate */
            rate?: number | string | null;
            cancellation_policy?: components["schemas"]["CancellationPolicy"] | null;
            /** Pricing Options */
            pricing_options?: string[] | null;
            /** Deliverables */
            deliverables?: components["schemas"]["DeliverableIn"][] | null;
        };
        /**
         * ServiceType
         * @enum {string}
         */
        ServiceType: "Subscription" | "Usage Based" | "One Time" | "Project Based";
        /** SubscriptionIn */
        SubscriptionIn: {
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * Discount Pct
             * @default 0
             */
            discount_pct: number | string;
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /** Client Name */
            client_name?: string | null;
            /** Service Name */
            service_name?: string | null;
            billing_interval?: components["schemas"]["BillingInterval"] | null;
            /** Rate */
            rate?: string | null;
            /** Effective Rate */
            effective_rate?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Discount Pct */
            discount_pct: string;
            status: components["schemas"]["SubscriptionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubscriptionPatch */
        SubscriptionPatch: {
            status: components["schemas"]["SubscriptionStatus"];
        };
        /**
         * SubscriptionStatus
         * @enum {string}
         */
        SubscriptionStatus: "active" | "ended";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Username */
            username: string;
            role: components["schemas"]["Role"];
            org?: components["schemas"]["OrgSummary"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_org_api_org_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettingsOut"];
                };
            };
        };
    };
    update_org_api_org_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_organisations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_organisations__org_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organisations_api_admin_organisations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrgOut"][];
                };
            };
        };
    };
    create_organisation_api_admin_organisations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOrgIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_plan_api_admin_organisations__org_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPlanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_admin_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
        };
    };
    create_plan_api_admin_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_admin_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_admin_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_api_services_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ServiceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_api_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_api_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_service_api_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_api_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_clients_get: {
        parameters: {
            query?: {
                q?: string | null;
                lifecycle_stage?: components["schemas"]["LifecycleStage"] | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_client_api_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_clients__client_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_clients__client_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_subscriptions_api_clients__client_id__subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_api_clients__client_id__subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_invoices_api_clients__client_id__invoices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_enrollments_api_clients__client_id__enrollments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instructors_api_instructors_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InstructorOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instructor_api_instructors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstructorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instructor_api_instructors__instructor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_instructor_api_instructors__instructor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instructor_api_instructors__instructor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstructorPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batches_taught_api_instructors__instructor_id__batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LocationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_api_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_location_api_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_location_api_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_batches_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_batch_api_batches__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_batch_api_batches__batch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_roster_api_batches__batch_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enrollments_api_enrollments_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EnrollmentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_enrollment_api_enrollments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subscription_api_subscriptions__subscription_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_invoices_get: {
        parameters: {
            query?: {
                status?: string | null;
                client_id?: string | null;
                q?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_missing_invoices_api_invoices_generate_missing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMissingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateMissingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_invoice_api_invoices__invoice_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
