"""initial schema

Revision ID: 2b022badd088
Revises: 
Create Date: 2026-07-21 00:08:36.510606

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b022badd088'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('no_of_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('subscription_plan_name_ci_key', 'subscription_plan', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('organisation',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_starts_on', sa.Date(), nullable=True),
    sa.Column('subscription_ends_on', sa.Date(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('invoice_prefix', sa.Text(), nullable=False),
    sa.Column('invoice_grace_days', sa.Integer(), nullable=False),
    sa.Column('capacity_policy', sa.Enum('warn', 'block', name='capacity_policy', native_enum=False, length=30), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_invoice_seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'staff', name='user_role', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("org_id IS NOT NULL OR role = 'superadmin'", name='app_user_orgless_is_superadmin'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'username', name='app_user_username_per_org')
    )
    op.create_index('app_user_platform_username_key', 'app_user', ['username'], unique=True, sqlite_where=sa.text('org_id IS NULL'), postgresql_where=sa.text('org_id IS NULL'))
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_table('client',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_hint', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('Female', 'Male', 'Non-binary', 'Prefer not to say', name='gender', native_enum=False, length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('lead_source', sa.Text(), nullable=True),
    sa.Column('lifecycle_stage', sa.Enum('Lead', 'Prospect', 'Customer', 'Lapsed', name='lifecycle_stage', native_enum=False, length=30), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('do_not_email', sa.Boolean(), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('work', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('account_type', sa.Enum('Individual', 'Corporate', 'Family', name='account_type', native_enum=False, length=30), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('company_contact', sa.Text(), nullable=True),
    sa.Column('family_link_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_link_id'], ['client.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_org_id'), 'client', ['org_id'], unique=False)
    op.create_table('instructor',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('experience_at_joining', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('courses', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_org_id'), 'instructor', ['org_id'], unique=False)
    op.create_table('location',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capacity_per_batch', sa.Integer(), nullable=True),
    sa.Column('parallel_batches', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='location_code_per_org')
    )
    op.create_index(op.f('ix_location_org_id'), 'location', ['org_id'], unique=False)
    op.create_table('service',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Enum('Subscription', 'Usage Based', 'One Time', 'Project Based', name='service_type', native_enum=False, length=30), nullable=False),
    sa.Column('delivery_mode', sa.Enum('Offline', 'Online', 'Hybrid', 'Self Service', name='delivery_mode', native_enum=False, length=30), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('billing_interval', sa.Enum('N/A', 'Monthly', 'Weekly', 'Quarterly', 'Semi-Annual', 'Annual', name='billing_interval', native_enum=False, length=30), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cancellation_policy', sa.Enum('Non-Refundable', 'Flexible', 'Moderate', 'Strict', name='cancellation_policy', native_enum=False, length=30), nullable=False),
    sa.Column('pricing_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'sku', name='service_sku_per_org')
    )
    op.create_index(op.f('ix_service_org_id'), 'service', ['org_id'], unique=False)
    op.create_table('batch',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'upcoming', 'completed', name='batch_status', native_enum=False, length=30), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='batch_dates_ordered'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='batch_code_per_org')
    )
    op.create_index(op.f('ix_batch_instructor_id'), 'batch', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_batch_location_id'), 'batch', ['location_id'], unique=False)
    op.create_index(op.f('ix_batch_org_id'), 'batch', ['org_id'], unique=False)
    op.create_table('contact_note',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_note_client_id'), 'contact_note', ['client_id'], unique=False)
    op.create_table('service_deliverable',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_deliverable_service_id'), 'service_deliverable', ['service_id'], unique=False)
    op.create_table('subscription',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='subscription_status', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_client_id'), 'subscription', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscription_service_id'), 'subscription', ['service_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'client_id', name='enrollment_once_per_batch')
    )
    op.create_index(op.f('ix_enrollment_batch_id'), 'enrollment', ['batch_id'], unique=False)
    op.create_index(op.f('ix_enrollment_client_id'), 'enrollment', ['client_id'], unique=False)
    op.create_table('invoice',
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('period_label', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('due', 'paid', 'void', name='invoice_status', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'period_label', name='invoice_one_per_period')
    )
    op.create_index(op.f('ix_invoice_client_id'), 'invoice', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoice_number'), 'invoice', ['number'], unique=False)
    op.create_index(op.f('ix_invoice_subscription_id'), 'invoice', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_subscription_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_client_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_enrollment_client_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_batch_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_subscription_service_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_client_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_service_deliverable_service_id'), table_name='service_deliverable')
    op.drop_table('service_deliverable')
    op.drop_index(op.f('ix_contact_note_client_id'), table_name='contact_note')
    op.drop_table('contact_note')
    op.drop_index(op.f('ix_batch_org_id'), table_name='batch')
    op.drop_index(op.f('ix_batch_location_id'), table_name='batch')
    op.drop_index(op.f('ix_batch_instructor_id'), table_name='batch')
    op.drop_table('batch')
    op.drop_index(op.f('ix_service_org_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_location_org_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_instructor_org_id'), table_name='instructor')
    op.drop_table('instructor')
    op.drop_index(op.f('ix_client_org_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_index('app_user_platform_username_key', table_name='app_user', sqlite_where=sa.text('org_id IS NULL'), postgresql_where=sa.text('org_id IS NULL'))
    op.drop_table('app_user')
    op.drop_table('organisation')
    op.drop_index('subscription_plan_name_ci_key', table_name='subscription_plan')
    op.drop_table('subscription_plan')
    # ### end Alembic commands ###
