"""drop client account_type

Revision ID: 6ff8b252a0ed
Revises: c8e0a2f4b6d7
Create Date: 2026-08-15 23:29:23.690936

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ff8b252a0ed"
down_revision: str | Sequence[str] | None = "c8e0a2f4b6d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "account_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "account_type",
            sa.VARCHAR(length=30),
            server_default="Individual",
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
